import React from 'react';

export interface MainDashboardProps {
  title?: string;
}

export const MainDashboard: React.FC<MainDashboardProps> = ({ title = 'MainDashboard' }) => {
  return (
    <div className="maindashboard-container" style={{ padding: '10px', border: '1px solid #ccc' }}>
      <h3>{title}</h3>
      <p>MainDashboard generated by CreatorCode Builder Agent</p>
    </div>
  );
};

export default MainDashboard;
